services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: careerwise_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    command: ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: ./careerwise-frontend
      dockerfile: Dockerfile
    container_name: careerwise_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
