version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: careerwise_backend
    ports:
      - "10000:10000"   # Expose backend for direct access if needed
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    command: ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "10000", "--reload"]

  frontend:
    build:
      context: ./careerwise-frontend
      dockerfile: Dockerfile
    container_name: careerwise_frontend
    ports:
      - "3000:80"  # Expose frontend on port 3000
    depends_on:
      - backend
