version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: careerwise_backend
    ports:
      - "10000:10000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    depends_on:
      - frontend
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: careerwise_frontend
    ports:
      - "3000:80"  # Nginx serves frontend on port 80 inside container
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:10000
