version: "3.9"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: careerwise_backend
    ports:
      - "10000:10000"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./careerwise-frontend
      dockerfile: Dockerfile
    container_name: careerwise_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
